### ISSUE TITLE
Enabling CORS on Elasticsearch server

### ISSUE THREAD

**Issue by sschuepbach** [dataramblers/datahack-server-ansible#3]
Lieber @tobinski
Ich kriege beim Versuch, mit der Angular-App auf ES zuzugreifen, folgende Fehlermeldung:
> Failed to load http://es.dataramblers.io/sah/_search: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

Der notwendige Header wird laut [ES-Doku](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) mitgeschickt, wenn in `elasticsearch.yml` `http.cors.enabled: true` gesetzt ist.

**Comment by tobinski** [comment]
Wir müssen wohl die config elasticsearch.yml generieren und danach in den container mounten. In der docu gibt es dazu ein [Beispiel](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_b_bind_mounted_configuration)

**Comment by tobinski** [comment]
Weil wir einen reverse proxy nützen, muss dieser CORS handlen. Entsprechend müssen wir die Konfiguration des ngnix proxy anpassen
